export const theme = {
  colors: {
    primary: '#3B82F6',
    secondary: '#60A5FA',
    cta: '#F97316',
    background: '#F8FAFC',
    text: '#1E293B',
    textMuted: '#475569',
    border: '#E2E8F0',
    surface: '#FFFFFF',
    success: '#22c55e',
    error: '#ef4444',
  },
  typography: {
    fontFamily: 'Plus Jakarta Sans',
    sizes: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 20,
      xl: 24,
      xxl: 32,
    },
    weights: {
      light: '300',
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.18,
      shadowRadius: 1.0,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
  },
};
